package Admin;
import UserLogin.LoginPage;
import InventoryManager.IMForm;

import javax.swing.*;
import java.awt.event.*;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import InventoryManager.InvenUser;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.*;
import javax.swing.table.DefaultTableCellRenderer;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.TableRowSorter;



public class AdminPanel extends javax.swing.JFrame {
    CardLayout AdminLayout;
    Admin admin = new Admin();    
        
        // Initialize a hashmap for user roles
        private Map<String, String> roleMap = new HashMap<>() {{
            put("Admin", "Admin");
            put("Sales Manager", "SM");
            put("Purchase Manager", "PM");
            put("Finance Manager", "FM");
            put("Inventory Manager", "IM"); 
        }};
         
    public AdminPanel(String username, String password) {
        initComponents();
        this.AdminLayout = (CardLayout)(AdminMainPanel.getLayout());
        AdminLayout.show(AdminMainPanel, "HomeCard");
        buildUserTable();
    }
    public AdminPanel(boolean SA){
        initComponents();
        if(SA == true){
            admin = new SuperAdmin();
        }  
        System.out.println(admin.getClass());
    }

        private void homePageLoad(String username, String role){
        this.AdminLayout = (CardLayout)(AdminMainPanel.getLayout());
        AdminLayout.show(AdminMainPanel, "HomeCard");  
        admin.checkAlert(username, role);
        jLabel11.setText("Welcome User: " + username);
        jLabel10.setText("Role: " + role);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminMainPanel = new javax.swing.JPanel();
        SMPanel = new javax.swing.JPanel();
        PMPanel = new javax.swing.JPanel();
        IMPanel = new javax.swing.JPanel();
        FMPanel = new javax.swing.JPanel();
        AdminHPPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ManageUserP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        UserMPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RoleBox = new javax.swing.JComboBox<>();
        UserNBox = new javax.swing.JTextField();
        PasswdBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AddUBtn = new javax.swing.JButton();
        DeleteUBtn = new javax.swing.JButton();
        UpdateUBtn = new javax.swing.JButton();
        DelUserBox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        FilterPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RoleFilterBox = new javax.swing.JComboBox<>();
        FilterButton = new javax.swing.JButton();
        AdminSidePanel = new javax.swing.JPanel();
        SMBtn = new javax.swing.JButton();
        IMBtn = new javax.swing.JButton();
        ManageUsersBtn = new javax.swing.JButton();
        FMBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        PMBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 490));
        setResizable(false);

        AdminMainPanel.setLayout(new java.awt.CardLayout());

        SMPanel.setBackground(new java.awt.Color(0, 153, 51));
        SMPanel.setPreferredSize(new java.awt.Dimension(585, 478));

        javax.swing.GroupLayout SMPanelLayout = new javax.swing.GroupLayout(SMPanel);
        SMPanel.setLayout(SMPanelLayout);
        SMPanelLayout.setHorizontalGroup(
            SMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        SMPanelLayout.setVerticalGroup(
            SMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        AdminMainPanel.add(SMPanel, "SMCard");

        PMPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout PMPanelLayout = new javax.swing.GroupLayout(PMPanel);
        PMPanel.setLayout(PMPanelLayout);
        PMPanelLayout.setHorizontalGroup(
            PMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        PMPanelLayout.setVerticalGroup(
            PMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        AdminMainPanel.add(PMPanel, "PMCard");

        IMPanel.setBackground(new java.awt.Color(255, 204, 204));
        IMPanel.setPreferredSize(new java.awt.Dimension(585, 478));

        javax.swing.GroupLayout IMPanelLayout = new javax.swing.GroupLayout(IMPanel);
        IMPanel.setLayout(IMPanelLayout);
        IMPanelLayout.setHorizontalGroup(
            IMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        IMPanelLayout.setVerticalGroup(
            IMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        AdminMainPanel.add(IMPanel, "IMCard");

        FMPanel.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout FMPanelLayout = new javax.swing.GroupLayout(FMPanel);
        FMPanel.setLayout(FMPanelLayout);
        FMPanelLayout.setHorizontalGroup(
            FMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        FMPanelLayout.setVerticalGroup(
            FMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        AdminMainPanel.add(FMPanel, "FMCard");

        AdminHPPanel.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Admin HomePage");

        javax.swing.GroupLayout AdminHPPanelLayout = new javax.swing.GroupLayout(AdminHPPanel);
        AdminHPPanel.setLayout(AdminHPPanelLayout);
        AdminHPPanelLayout.setHorizontalGroup(
            AdminHPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHPPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        AdminHPPanelLayout.setVerticalGroup(
            AdminHPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHPPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        AdminMainPanel.add(AdminHPPanel, "HomeCard");

        ManageUserP.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("     User Management:");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Password", "Role"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        UserMPanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("User Details: ");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Username:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Role:");

        RoleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Role", "Sales Manager", "Purchase Manager", "Finance Manager", "Admin", "Inventory Manager" }));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Functions:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Add new user:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Delete user:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Update user:");

        AddUBtn.setText("Add ");
        AddUBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUBtnActionPerformed(evt);
            }
        });

        DeleteUBtn.setText("Delete");
        DeleteUBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUBtnActionPerformed(evt);
            }
        });

        UpdateUBtn.setText("Update ");
        UpdateUBtn.setToolTipText("");
        UpdateUBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUBtnActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Username:");

        javax.swing.GroupLayout UserMPanelLayout = new javax.swing.GroupLayout(UserMPanel);
        UserMPanel.setLayout(UserMPanelLayout);
        UserMPanelLayout.setHorizontalGroup(
            UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserMPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RoleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(UserMPanelLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(PasswdBox))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(UserMPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(UserNBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DeleteUBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(UserMPanelLayout.createSequentialGroup()
                            .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)
                                .addGroup(UserMPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel14))))
                            .addGap(18, 18, 18)
                            .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UpdateUBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AddUBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DelUserBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        UserMPanelLayout.setVerticalGroup(
            UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UserNBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PasswdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RoleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AddUBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(UpdateUBtn))
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelUserBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(DeleteUBtn))
        );

        FilterPanel.setBackground(new java.awt.Color(255, 204, 153));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Filters:");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Role:");

        RoleFilterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Admin", "Sales Manager", "Purchase Manager", "Finance Manager", "Inventory Manager" }));

        FilterButton.setText("Filter");
        FilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FilterPanelLayout = new javax.swing.GroupLayout(FilterPanel);
        FilterPanel.setLayout(FilterPanelLayout);
        FilterPanelLayout.setHorizontalGroup(
            FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FilterPanelLayout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RoleFilterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FilterPanelLayout.setVerticalGroup(
            FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(RoleFilterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FilterButton))
        );

        javax.swing.GroupLayout ManageUserPLayout = new javax.swing.GroupLayout(ManageUserP);
        ManageUserP.setLayout(ManageUserPLayout);
        ManageUserPLayout.setHorizontalGroup(
            ManageUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageUserPLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ManageUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageUserPLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManageUserPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManageUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserMPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        ManageUserPLayout.setVerticalGroup(
            ManageUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageUserPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(ManageUserPLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserMPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        AdminMainPanel.add(ManageUserP, "ManageUserCard");

        AdminSidePanel.setBackground(new java.awt.Color(153, 153, 153));

        SMBtn.setBackground(new java.awt.Color(204, 102, 0));
        SMBtn.setForeground(new java.awt.Color(0, 0, 0));
        SMBtn.setText("Sales Manager");
        SMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMBtnActionPerformed(evt);
            }
        });

        IMBtn.setBackground(new java.awt.Color(204, 102, 0));
        IMBtn.setForeground(new java.awt.Color(0, 0, 0));
        IMBtn.setText("Inventory Manager");
        IMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMBtnActionPerformed(evt);
            }
        });

        ManageUsersBtn.setBackground(new java.awt.Color(204, 102, 0));
        ManageUsersBtn.setForeground(new java.awt.Color(0, 0, 0));
        ManageUsersBtn.setText("Manage Users");
        ManageUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUsersBtnActionPerformed(evt);
            }
        });

        FMBtn.setBackground(new java.awt.Color(204, 102, 0));
        FMBtn.setForeground(new java.awt.Color(0, 0, 0));
        FMBtn.setText("Finance Manager");
        FMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMBtnActionPerformed(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(204, 102, 0));
        HomeBtn.setForeground(new java.awt.Color(0, 0, 0));
        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setBackground(new java.awt.Color(204, 102, 0));
        LogoutBtn.setForeground(new java.awt.Color(0, 0, 0));
        LogoutBtn.setText("Log out");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        PMBtn.setBackground(new java.awt.Color(204, 102, 0));
        PMBtn.setForeground(new java.awt.Color(0, 0, 0));
        PMBtn.setText("Purchase Manager");
        PMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mega (3).png"))); // NOI18N

        javax.swing.GroupLayout AdminSidePanelLayout = new javax.swing.GroupLayout(AdminSidePanel);
        AdminSidePanel.setLayout(AdminSidePanelLayout);
        AdminSidePanelLayout.setHorizontalGroup(
            AdminSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminSidePanelLayout.createSequentialGroup()
                .addGroup(AdminSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminSidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AdminSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminSidePanelLayout.createSequentialGroup()
                                .addComponent(LogoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SMBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageUsersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FMBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IMBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PMBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        AdminSidePanelLayout.setVerticalGroup(
            AdminSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminSidePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageUsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogoutBtn)
                    .addComponent(HomeBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(AdminSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(AdminSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void SMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMBtnActionPerformed
       AdminLayout.show(AdminMainPanel, "SMCard");
    }//GEN-LAST:event_SMBtnActionPerformed

    private void ManageUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUsersBtnActionPerformed
        AdminLayout.show(AdminMainPanel, "ManageUserCard");
    }//GEN-LAST:event_ManageUsersBtnActionPerformed

    private void PMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMBtnActionPerformed
        AdminLayout.show(AdminMainPanel, "PMCard");
    }//GEN-LAST:event_PMBtnActionPerformed

    private void IMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMBtnActionPerformed
        launchRoleDashboard("im4", "p18", "IM", this);
    }//GEN-LAST:event_IMBtnActionPerformed

    private void FMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMBtnActionPerformed
        AdminLayout.show(AdminMainPanel, "FMCard");
    }//GEN-LAST:event_FMBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        AdminLayout.show(AdminMainPanel, "HomeCard");
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void UpdateUBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUBtnActionPerformed
       admin.UpdateUser(UserNBox.getText(), PasswdBox.getText(), roleMap.get(RoleBox.getSelectedItem()));
       buildUserTable();
        UserNBox.setText("");
        PasswdBox.setText("");
        RoleBox.setSelectedIndex(0);
    }//GEN-LAST:event_UpdateUBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        LoginPage loginpage = new LoginPage();
        loginpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void AddUBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUBtnActionPerformed
          admin.AddUser(UserNBox.getText(), PasswdBox.getText(), roleMap.get(RoleBox.getSelectedItem()));
          buildUserTable();
          UserNBox.setText("");
          PasswdBox.setText("");
          RoleBox.setSelectedIndex(0);
    }//GEN-LAST:event_AddUBtnActionPerformed

    private void DeleteUBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUBtnActionPerformed
        admin.DeleteUser(DelUserBox.getText());
        buildUserTable();
        DelUserBox.setText("");
    }//GEN-LAST:event_DeleteUBtnActionPerformed

    private void FilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterButtonActionPerformed
        RoleFilter();
    }//GEN-LAST:event_FilterButtonActionPerformed

    
    public void buildUserTable(){
        userTable.getTableHeader().setReorderingAllowed(false);
        userTable.getTableHeader().setResizingAllowed(false);
        userTable.enableInputMethods(false);
        userTable.setRowSelectionAllowed(true);
        
        // Refresh the user list from file 
        admin.reloadUsers();
        
        // Load the existing table model generated by Netbeans
        DefaultTableModel Usermodel = (DefaultTableModel) userTable.getModel();
        
        // Clear any existing rows
        Usermodel.setRowCount(0);
        
        // Add users from the UserList
        for (List<String> user: admin.UserList){
            Usermodel.addRow(new Object[]{
            user.get(0),
            user.get(1),
            user.get(2),
            user.get(3)
        });
        }
    }
    
    public void RoleFilter(){
        DefaultTableModel Usermodel = (DefaultTableModel) userTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(Usermodel);
        userTable.setRowSorter(sorter);
        
        String selectedRole = (String) RoleFilterBox.getSelectedItem();
        String rolecode = roleMap.get(selectedRole);
        
        if (selectedRole.equalsIgnoreCase("All")){
            sorter.setRowFilter(null);
        }
        else if (selectedRole.equalsIgnoreCase("Admin")){
            sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + rolecode + "$", 3));
        }
        else if (selectedRole.equalsIgnoreCase("Sales Manager")){
            sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + rolecode + "$", 3));
        }
        else if (selectedRole.equalsIgnoreCase("Purchase Manager")){
            sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + rolecode + "$", 3));
        }
        else if (selectedRole.equalsIgnoreCase("Finance Manager")){
            sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + rolecode + "$", 3));
        }
        else if (selectedRole.equalsIgnoreCase("Inventory Manager")){
            sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + rolecode + "$", 3));
        }
        buildUserTable();
    }
    
    public void launchRoleDashboard(String username, String password, String role, JFrame adminFrame) {
        switch (role) {
            case "IM" -> new IMForm(username, password, adminFrame).setVisible(true);
            default -> JOptionPane.showMessageDialog(null, "Invalid role!");
        }
    //        case "SM":
    //            new SMForm(username, password, adminFrame).setVisible(true);
    //            break;
    //        case "PM":
    //            new PMForm(username, password, adminFrame).setVisible(true);
    //            break;
    //        case "FM":
    //            new FMForm(username, password, adminFrame).setVisible(true);
    //            break;

        if (adminFrame != null) {
            adminFrame.setVisible(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel("adm2", "p6").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUBtn;
    private javax.swing.JPanel AdminHPPanel;
    private javax.swing.JPanel AdminMainPanel;
    private javax.swing.JPanel AdminSidePanel;
    private javax.swing.JTextField DelUserBox;
    private javax.swing.JButton DeleteUBtn;
    private javax.swing.JButton FMBtn;
    private javax.swing.JPanel FMPanel;
    private javax.swing.JButton FilterButton;
    private javax.swing.JPanel FilterPanel;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton IMBtn;
    private javax.swing.JPanel IMPanel;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel ManageUserP;
    private javax.swing.JButton ManageUsersBtn;
    private javax.swing.JButton PMBtn;
    private javax.swing.JPanel PMPanel;
    private javax.swing.JTextField PasswdBox;
    private javax.swing.JComboBox<String> RoleBox;
    private javax.swing.JComboBox<String> RoleFilterBox;
    private javax.swing.JButton SMBtn;
    private javax.swing.JPanel SMPanel;
    private javax.swing.JButton UpdateUBtn;
    private javax.swing.JPanel UserMPanel;
    private javax.swing.JTextField UserNBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
