/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SM;

/**
 *
 * @author dhoom
 */
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.*;
import java.awt.*;
public class SalesManagerDashboard extends javax.swing.JFrame {

    public SalesManagerDashboard() {
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        btnViewItems = new javax.swing.JButton();
        btnViewSuppliers = new javax.swing.JButton();
        btnViewPRs = new javax.swing.JButton();
        btnViewSales = new javax.swing.JButton();
        btnViewOP = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setLayout(new java.awt.GridLayout(6, 1));

        btnViewItems.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        btnViewItems.setText(" Items");
        btnViewItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemsActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnViewItems);

        btnViewSuppliers.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnViewSuppliers.setText(" Suppliers");
        btnViewSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSuppliersActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnViewSuppliers);

        btnViewPRs.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnViewPRs.setText(" PRs");
        btnViewPRs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPRsActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnViewPRs);

        btnViewSales.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnViewSales.setText("Sales");
        btnViewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSalesActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnViewSales);

        btnViewOP.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnViewOP.setText("View OP");
        btnViewOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOPActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnViewOP);

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnExit.setText("Exit");
        sidebarPanel.add(btnExit);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome Sales Manager ");
        contentPanel.add(jLabel1);

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemsActionPerformed
        contentPanel.removeAll();
        contentPanel.add(new ItemEntryPanel());
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_btnViewItemsActionPerformed

    private void btnViewSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSuppliersActionPerformed
        contentPanel.removeAll();  
        SupplierEntryPanel supplierPanel = new SupplierEntryPanel();  
        contentPanel.add(supplierPanel);
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_btnViewSuppliersActionPerformed

    private void btnViewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSalesActionPerformed
        contentPanel.removeAll();  
        DailySalesEntryPanel salesPanel = new DailySalesEntryPanel();  
        contentPanel.add(salesPanel);
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_btnViewSalesActionPerformed

    private void btnViewPRsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPRsActionPerformed
        contentPanel.removeAll();
        PRPanel prPanel = new PRPanel();  
        contentPanel.add(prPanel);
        contentPanel.revalidate();
        contentPanel.repaint();

    }//GEN-LAST:event_btnViewPRsActionPerformed

    private void btnViewOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOPActionPerformed
    contentPanel.removeAll();  
    POViewPanel viewPanel = new POViewPanel();  
    contentPanel.add(viewPanel); 
    contentPanel.revalidate();  
    contentPanel.repaint();
    }//GEN-LAST:event_btnViewOPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnViewItems;
    private javax.swing.JButton btnViewOP;
    private javax.swing.JButton btnViewPRs;
    private javax.swing.JButton btnViewSales;
    private javax.swing.JButton btnViewSuppliers;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
