/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SM;

/**
 *
 * @author dhoom
 */
import java.awt.CardLayout;

public class SMForm extends javax.swing.JFrame {

    /**
     * Creates new form SMForm
     */
    public SMForm() {
        initComponents();
        panelMainContent.add(panelItemManagement, "panelItemManagement");
        panelMainContent.add(panelSupplierManagement, "panelSupplierManagement");
        panelMainContent.add(panelDailySalesEntry, "panelDailySalesEntry");
        panelMainContent.add(panelPurchaseRequisition, "panelPurchaseRequisition");
        panelMainContent.add(panelDisplayRequisition, "panelDisplayRequisition");
        panelMainContent.add(panelViewPurchaseOrders, "panelViewPurchaseOrders");
        
        jPanel1.add(AddItem, "AddItem");
        jPanel1.add(EditItem, "DeleteItem");
        jPanel1.add(DeleteItem, "EditItem");
        jPanel1.add(ViewItem, "ViewItem");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        panelSidebar = new javax.swing.JPanel();
        Item_M = new javax.swing.JButton();
        Supplier_M = new javax.swing.JButton();
        Daily_S_E = new javax.swing.JButton();
        Purchase_R = new javax.swing.JButton();
        Display_R = new javax.swing.JButton();
        View_P_O = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        panelMainContent = new javax.swing.JPanel();
        panelWelcome = new javax.swing.JPanel();
        panelItemManagement = new javax.swing.JPanel();
        btnAddItemForm = new javax.swing.JButton();
        btnEditItemForm = new javax.swing.JButton();
        btnDeleteItemForm = new javax.swing.JButton();
        btnViewItemForm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AddItem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnSaveItem = new javax.swing.JButton();
        EditItem = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSearchItemCode = new javax.swing.JTextField();
        btnSearchItem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEditItemName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEditQuantity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEditPrice = new javax.swing.JTextField();
        btnSaveChanges = new javax.swing.JButton();
        DeleteItem = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnDeleteItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_deletitem = new javax.swing.JTable();
        ViewItem = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        panelSupplierManagement = new javax.swing.JPanel();
        panelDailySalesEntry = new javax.swing.JPanel();
        panelPurchaseRequisition = new javax.swing.JPanel();
        panelDisplayRequisition = new javax.swing.JPanel();
        panelViewPurchaseOrders = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setLayout(new java.awt.BorderLayout());

        panelSidebar.setBackground(new java.awt.Color(0, 204, 204));

        Item_M.setText("Item Management");
        Item_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MActionPerformed(evt);
            }
        });

        Supplier_M.setText("Supplier Management  ");
        Supplier_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_MActionPerformed(evt);
            }
        });

        Daily_S_E.setText("Daily Sales Entry  ");
        Daily_S_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Daily_S_EActionPerformed(evt);
            }
        });

        Purchase_R.setText("Purchase Requisition");
        Purchase_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_RActionPerformed(evt);
            }
        });

        Display_R.setText("Display Requisitions");
        Display_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display_RActionPerformed(evt);
            }
        });

        View_P_O.setText("View Purchase Orders");
        View_P_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_P_OActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item_M, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Supplier_M, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Daily_S_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Purchase_R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Display_R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(View_P_O, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Item_M, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Supplier_M, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Daily_S_E, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Purchase_R, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Display_R, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(View_P_O, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMainContent.setBackground(new java.awt.Color(0, 204, 51));
        panelMainContent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelWelcome, "card8");

        panelItemManagement.setBackground(new java.awt.Color(204, 204, 204));

        btnAddItemForm.setText("Add");
        btnAddItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemFormActionPerformed(evt);
            }
        });

        btnEditItemForm.setText("Edit");
        btnEditItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditItemFormActionPerformed(evt);
            }
        });

        btnDeleteItemForm.setText("Delete");
        btnDeleteItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemFormActionPerformed(evt);
            }
        });

        btnViewItemForm.setText("View");
        btnViewItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemFormActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        AddItem.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setText("Add New Item");

        jLabel3.setText("Name:");

        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Qِuantity:");

        jLabel4.setText("Code:");

        jLabel5.setText("Price:");

        btnSaveItem.setText("Save");

        javax.swing.GroupLayout AddItemLayout = new javax.swing.GroupLayout(AddItem);
        AddItem.setLayout(AddItemLayout);
        AddItemLayout.setHorizontalGroup(
            AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddItemLayout.createSequentialGroup()
                .addGroup(AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddItemLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddItemLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddItemLayout.createSequentialGroup()
                                .addGroup(AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrice)))))
                    .addGroup(AddItemLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnSaveItem)))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        AddItemLayout.setVerticalGroup(
            AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveItem)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanel1.add(AddItem, "card2");

        EditItem.setBackground(new java.awt.Color(0, 255, 102));

        jLabel6.setText("Edit Item");

        btnSearchItem.setText("Search");

        jLabel7.setText("Item Code:");

        jLabel8.setText("Item Name:");

        jLabel9.setText("Quantity:");

        jLabel10.setText("Price:");

        btnSaveChanges.setText("Save Changes");

        javax.swing.GroupLayout EditItemLayout = new javax.swing.GroupLayout(EditItem);
        EditItem.setLayout(EditItemLayout);
        EditItemLayout.setHorizontalGroup(
            EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditItemLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditItemLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EditItemLayout.createSequentialGroup()
                        .addComponent(txtSearchItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                        .addComponent(btnSearchItem)
                        .addGap(119, 119, 119))))
            .addGroup(EditItemLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSaveChanges, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtEditPrice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditItemName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEditQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditItemLayout.setVerticalGroup(
            EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditItemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveChanges)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(EditItem, "card3");

        DeleteItem.setBackground(new java.awt.Color(255, 255, 0));

        jLabel11.setText("Delete Item");

        btnDeleteItem.setText("Delete");

        Table_deletitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Item Code", "Quantity  ", "Price"
            }
        ));
        jScrollPane2.setViewportView(Table_deletitem);

        javax.swing.GroupLayout DeleteItemLayout = new javax.swing.GroupLayout(DeleteItem);
        DeleteItem.setLayout(DeleteItemLayout);
        DeleteItemLayout.setHorizontalGroup(
            DeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteItemLayout.createSequentialGroup()
                .addGroup(DeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteItemLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteItemLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteItemLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnDeleteItem)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        DeleteItemLayout.setVerticalGroup(
            DeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDeleteItem)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel1.add(DeleteItem, "card4");

        jLabel13.setText("View Items");

        tableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Item Code", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(tableItems);

        javax.swing.GroupLayout ViewItemLayout = new javax.swing.GroupLayout(ViewItem);
        ViewItem.setLayout(ViewItemLayout);
        ViewItemLayout.setHorizontalGroup(
            ViewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewItemLayout.createSequentialGroup()
                .addGroup(ViewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewItemLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewItemLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        ViewItemLayout.setVerticalGroup(
            ViewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewItemLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.add(ViewItem, "card5");

        javax.swing.GroupLayout panelItemManagementLayout = new javax.swing.GroupLayout(panelItemManagement);
        panelItemManagement.setLayout(panelItemManagementLayout);
        panelItemManagementLayout.setHorizontalGroup(
            panelItemManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelItemManagementLayout.createSequentialGroup()
                .addComponent(btnAddItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelItemManagementLayout.setVerticalGroup(
            panelItemManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItemManagementLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelItemManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditItemForm)
                    .addComponent(btnDeleteItemForm)
                    .addComponent(btnViewItemForm)
                    .addComponent(btnAddItemForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        panelMainContent.add(panelItemManagement, "card2");

        panelSupplierManagement.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelSupplierManagementLayout = new javax.swing.GroupLayout(panelSupplierManagement);
        panelSupplierManagement.setLayout(panelSupplierManagementLayout);
        panelSupplierManagementLayout.setHorizontalGroup(
            panelSupplierManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        panelSupplierManagementLayout.setVerticalGroup(
            panelSupplierManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelSupplierManagement, "card3");

        panelDailySalesEntry.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout panelDailySalesEntryLayout = new javax.swing.GroupLayout(panelDailySalesEntry);
        panelDailySalesEntry.setLayout(panelDailySalesEntryLayout);
        panelDailySalesEntryLayout.setHorizontalGroup(
            panelDailySalesEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        panelDailySalesEntryLayout.setVerticalGroup(
            panelDailySalesEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelDailySalesEntry, "card4");

        panelPurchaseRequisition.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout panelPurchaseRequisitionLayout = new javax.swing.GroupLayout(panelPurchaseRequisition);
        panelPurchaseRequisition.setLayout(panelPurchaseRequisitionLayout);
        panelPurchaseRequisitionLayout.setHorizontalGroup(
            panelPurchaseRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        panelPurchaseRequisitionLayout.setVerticalGroup(
            panelPurchaseRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelPurchaseRequisition, "card5");

        panelDisplayRequisition.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelDisplayRequisitionLayout = new javax.swing.GroupLayout(panelDisplayRequisition);
        panelDisplayRequisition.setLayout(panelDisplayRequisitionLayout);
        panelDisplayRequisitionLayout.setHorizontalGroup(
            panelDisplayRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        panelDisplayRequisitionLayout.setVerticalGroup(
            panelDisplayRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelDisplayRequisition, "card6");

        panelViewPurchaseOrders.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout panelViewPurchaseOrdersLayout = new javax.swing.GroupLayout(panelViewPurchaseOrders);
        panelViewPurchaseOrders.setLayout(panelViewPurchaseOrdersLayout);
        panelViewPurchaseOrdersLayout.setHorizontalGroup(
            panelViewPurchaseOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        panelViewPurchaseOrdersLayout.setVerticalGroup(
            panelViewPurchaseOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelViewPurchaseOrders, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MActionPerformed
        CardLayout cl = (CardLayout)(panelMainContent.getLayout());
        cl.show(panelMainContent, "panelItemManagement");
    }//GEN-LAST:event_Item_MActionPerformed

    private void Supplier_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_MActionPerformed
      CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelSupplierManagement");
    }//GEN-LAST:event_Supplier_MActionPerformed

    private void Daily_S_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Daily_S_EActionPerformed
       CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelDailySalesEntry");
    }//GEN-LAST:event_Daily_S_EActionPerformed

    private void Purchase_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_RActionPerformed
        CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelPurchaseRequisition");
    }//GEN-LAST:event_Purchase_RActionPerformed

    private void Display_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display_RActionPerformed
      CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelDisplayRequisition");
    }//GEN-LAST:event_Display_RActionPerformed

    private void View_P_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_P_OActionPerformed
      CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelViewPurchaseOrders");
    }//GEN-LAST:event_View_P_OActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnEditItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditItemFormActionPerformed
      CardLayout cl = (CardLayout)(jPanel1.getLayout());
      cl.show(jPanel1, "EditItem");
    }//GEN-LAST:event_btnEditItemFormActionPerformed

    private void btnAddItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemFormActionPerformed
      CardLayout cl = (CardLayout)(jPanel1.getLayout());
      cl.show(jPanel1, "AddItem");
    }//GEN-LAST:event_btnAddItemFormActionPerformed

    private void btnDeleteItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemFormActionPerformed
      CardLayout cl = (CardLayout)(jPanel1.getLayout());
      cl.show(jPanel1, "DeleteItem");
    }//GEN-LAST:event_btnDeleteItemFormActionPerformed

    private void btnViewItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemFormActionPerformed
      CardLayout cl = (CardLayout)(jPanel1.getLayout());
      cl.show(jPanel1, "ViewItem");
    }//GEN-LAST:event_btnViewItemFormActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddItem;
    private javax.swing.JButton Daily_S_E;
    private javax.swing.JPanel DeleteItem;
    private javax.swing.JButton Display_R;
    private javax.swing.JPanel EditItem;
    private javax.swing.JButton Item_M;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel Main;
    private javax.swing.JButton Purchase_R;
    private javax.swing.JButton Supplier_M;
    private javax.swing.JTable Table_deletitem;
    private javax.swing.JPanel ViewItem;
    private javax.swing.JButton View_P_O;
    private javax.swing.JButton btnAddItemForm;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnDeleteItemForm;
    private javax.swing.JButton btnEditItemForm;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JButton btnSaveItem;
    private javax.swing.JButton btnSearchItem;
    private javax.swing.JButton btnViewItemForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDailySalesEntry;
    private javax.swing.JPanel panelDisplayRequisition;
    private javax.swing.JPanel panelItemManagement;
    private javax.swing.JPanel panelMainContent;
    private javax.swing.JPanel panelPurchaseRequisition;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelSupplierManagement;
    private javax.swing.JPanel panelViewPurchaseOrders;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JTable tableItems;
    private javax.swing.JTextField txtEditItemName;
    private javax.swing.JTextField txtEditPrice;
    private javax.swing.JTextField txtEditQuantity;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearchItemCode;
    // End of variables declaration//GEN-END:variables
}
