/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SM;

/**
 *
 * @author dhoom
 */
import java.awt.CardLayout;

public class SMForm extends javax.swing.JFrame {

    /**
     * Creates new form SMForm
     */
    public SMForm() {
        initComponents();
        panelMainContent.add(panelItemManagement, "panelItemManagement");
        panelMainContent.add(panelSupplierManagement, "panelSupplierManagement");
        panelMainContent.add(panelDailySalesEntry, "panelDailySalesEntry");
        panelMainContent.add(panelPurchaseRequisition, "panelPurchaseRequisition");
        panelMainContent.add(panelDisplayRequisition, "panelDisplayRequisition");
        panelMainContent.add(panelViewPurchaseOrders, "panelViewPurchaseOrders");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        panelSidebar = new javax.swing.JPanel();
        Item_M = new javax.swing.JButton();
        Supplier_M = new javax.swing.JButton();
        Daily_S_E = new javax.swing.JButton();
        Purchase_R = new javax.swing.JButton();
        Display_R = new javax.swing.JButton();
        View_P_O = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        panelMainContent = new javax.swing.JPanel();
        panelWelcome = new javax.swing.JPanel();
        panelItemManagement = new javax.swing.JPanel();
        btnAddItemForm = new javax.swing.JButton();
        btnEditItemForm = new javax.swing.JButton();
        btnDeleteItemForm = new javax.swing.JButton();
        btnViewItemForm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelSupplierManagement = new javax.swing.JPanel();
        panelDailySalesEntry = new javax.swing.JPanel();
        panelPurchaseRequisition = new javax.swing.JPanel();
        panelDisplayRequisition = new javax.swing.JPanel();
        panelViewPurchaseOrders = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setLayout(new java.awt.BorderLayout());

        panelSidebar.setBackground(new java.awt.Color(0, 204, 204));

        Item_M.setText("Item Management");
        Item_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MActionPerformed(evt);
            }
        });

        Supplier_M.setText("Supplier Management  ");
        Supplier_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_MActionPerformed(evt);
            }
        });

        Daily_S_E.setText("Daily Sales Entry  ");
        Daily_S_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Daily_S_EActionPerformed(evt);
            }
        });

        Purchase_R.setText("Purchase Requisition");
        Purchase_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_RActionPerformed(evt);
            }
        });

        Display_R.setText("Display Requisitions");
        Display_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display_RActionPerformed(evt);
            }
        });

        View_P_O.setText("View Purchase Orders");
        View_P_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_P_OActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item_M, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Supplier_M, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Daily_S_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Purchase_R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Display_R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(View_P_O, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Item_M, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Supplier_M, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Daily_S_E, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Purchase_R, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Display_R, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(View_P_O, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMainContent.setBackground(new java.awt.Color(0, 204, 51));
        panelMainContent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelWelcome, "card8");

        panelItemManagement.setBackground(new java.awt.Color(204, 204, 204));

        btnAddItemForm.setText("Add");

        btnEditItemForm.setText("Edit");

        btnDeleteItemForm.setText("Delete");

        btnViewItemForm.setText("View");

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(0, 255, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, "card3");

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, "card4");

        javax.swing.GroupLayout panelItemManagementLayout = new javax.swing.GroupLayout(panelItemManagement);
        panelItemManagement.setLayout(panelItemManagementLayout);
        panelItemManagementLayout.setHorizontalGroup(
            panelItemManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItemManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewItemForm, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(btnEditItemForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteItemForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddItemForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelItemManagementLayout.setVerticalGroup(
            panelItemManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemManagementLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAddItemForm)
                .addGap(43, 43, 43)
                .addComponent(btnEditItemForm)
                .addGap(44, 44, 44)
                .addComponent(btnDeleteItemForm)
                .addGap(46, 46, 46)
                .addComponent(btnViewItemForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelMainContent.add(panelItemManagement, "card2");

        panelSupplierManagement.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelSupplierManagementLayout = new javax.swing.GroupLayout(panelSupplierManagement);
        panelSupplierManagement.setLayout(panelSupplierManagementLayout);
        panelSupplierManagementLayout.setHorizontalGroup(
            panelSupplierManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        panelSupplierManagementLayout.setVerticalGroup(
            panelSupplierManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelSupplierManagement, "card3");

        panelDailySalesEntry.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout panelDailySalesEntryLayout = new javax.swing.GroupLayout(panelDailySalesEntry);
        panelDailySalesEntry.setLayout(panelDailySalesEntryLayout);
        panelDailySalesEntryLayout.setHorizontalGroup(
            panelDailySalesEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        panelDailySalesEntryLayout.setVerticalGroup(
            panelDailySalesEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelDailySalesEntry, "card4");

        panelPurchaseRequisition.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout panelPurchaseRequisitionLayout = new javax.swing.GroupLayout(panelPurchaseRequisition);
        panelPurchaseRequisition.setLayout(panelPurchaseRequisitionLayout);
        panelPurchaseRequisitionLayout.setHorizontalGroup(
            panelPurchaseRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        panelPurchaseRequisitionLayout.setVerticalGroup(
            panelPurchaseRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelPurchaseRequisition, "card5");

        panelDisplayRequisition.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelDisplayRequisitionLayout = new javax.swing.GroupLayout(panelDisplayRequisition);
        panelDisplayRequisition.setLayout(panelDisplayRequisitionLayout);
        panelDisplayRequisitionLayout.setHorizontalGroup(
            panelDisplayRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        panelDisplayRequisitionLayout.setVerticalGroup(
            panelDisplayRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelDisplayRequisition, "card6");

        panelViewPurchaseOrders.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout panelViewPurchaseOrdersLayout = new javax.swing.GroupLayout(panelViewPurchaseOrders);
        panelViewPurchaseOrders.setLayout(panelViewPurchaseOrdersLayout);
        panelViewPurchaseOrdersLayout.setHorizontalGroup(
            panelViewPurchaseOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        panelViewPurchaseOrdersLayout.setVerticalGroup(
            panelViewPurchaseOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        panelMainContent.add(panelViewPurchaseOrders, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MActionPerformed
        CardLayout cl = (CardLayout)(panelMainContent.getLayout());
        cl.show(panelMainContent, "panelItemManagement");
    }//GEN-LAST:event_Item_MActionPerformed

    private void Supplier_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_MActionPerformed
      CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelSupplierManagement");
    }//GEN-LAST:event_Supplier_MActionPerformed

    private void Daily_S_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Daily_S_EActionPerformed
       CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelDailySalesEntry");
    }//GEN-LAST:event_Daily_S_EActionPerformed

    private void Purchase_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_RActionPerformed
        CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelPurchaseRequisition");
    }//GEN-LAST:event_Purchase_RActionPerformed

    private void Display_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display_RActionPerformed
      CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelDisplayRequisition");
    }//GEN-LAST:event_Display_RActionPerformed

    private void View_P_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_P_OActionPerformed
      CardLayout cl = (CardLayout)(panelMainContent.getLayout());
      cl.show(panelMainContent, "panelViewPurchaseOrders");
    }//GEN-LAST:event_View_P_OActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Daily_S_E;
    private javax.swing.JButton Display_R;
    private javax.swing.JButton Item_M;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel Main;
    private javax.swing.JButton Purchase_R;
    private javax.swing.JButton Supplier_M;
    private javax.swing.JButton View_P_O;
    private javax.swing.JButton btnAddItemForm;
    private javax.swing.JButton btnDeleteItemForm;
    private javax.swing.JButton btnEditItemForm;
    private javax.swing.JButton btnViewItemForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelDailySalesEntry;
    private javax.swing.JPanel panelDisplayRequisition;
    private javax.swing.JPanel panelItemManagement;
    private javax.swing.JPanel panelMainContent;
    private javax.swing.JPanel panelPurchaseRequisition;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelSupplierManagement;
    private javax.swing.JPanel panelViewPurchaseOrders;
    private javax.swing.JPanel panelWelcome;
    // End of variables declaration//GEN-END:variables
}
