/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinanceManager.ui;

import javax.swing.*;
import FinanceManager.manager.*;
import javax.swing.table.DefaultTableModel;
import FinanceManager.model.*;

/**
 *
 * @author sumingfei
 */
public class FMForm extends javax.swing.JFrame {
    private PurchaseOrderManager poMgr = new PurchaseOrderManager();
    private PurchaseRequisitionManager prMgr = new PurchaseRequisitionManager();
    private SupplierManager supplierMgr = new SupplierManager();
    
    private DefaultTableModel tableModel;


    /**
     * Creates new form FMForm
     */
    public FMForm() {
        initComponents();
        // 1. Create and attach our table model
        tableModel = new DefaultTableModel(
        new String[]{"ID","Item","Qty","Status","Date"}, 
        0
        );
        tblRecords.setModel(tableModel);
    
        // 2. Wire up button clicks
        btnLoadPRs   .addActionListener(e -> loadPendingRequisitions());
        btnApprovePO .addActionListener(e -> approveSelected());
        btnLoadPOs   .addActionListener(e -> loadPendingOrders());
        btnProcessPay.addActionListener(e -> processPaymentForSelected());
        btnReport    .addActionListener(e -> showReportDialog());

        // 3. Perform an initial load
        loadPendingRequisitions();

        loadPendingPRs();
    }
    
    private void loadPendingRequisitions() {
    tableModel.setRowCount(0);
    for (PurchaseRequisition pr : prMgr.getAll()) {
        tableModel.addRow(new Object[]{
            pr.getId(),
            pr.getItemCode(),
            pr.getQuantity(),
            "REQUIRED",
            pr.getDateRequested()
        });
    }
}

    private void approveSelected() {
    int row = tblRecords.getSelectedRow();
    if (row < 0) return;
    int prId = (int) tableModel.getValueAt(row, 0);
    PurchaseRequisition pr = prMgr.findById(prId);        // you’ll need a findById method
    PurchaseOrder       po = new PurchaseOrder(pr);       // ctor that builds a PO from a PR
    poMgr.add(po);
    JOptionPane.showMessageDialog(this, "Created PO #" + po.getId());
    loadPendingRequisitions();
   }

    private void loadPendingOrders() {
    tableModel.setRowCount(0);
    for (PurchaseOrder po : poMgr.getAll()) {
        tableModel.addRow(new Object[]{
            po.getId(),
            po.getRequisition().getItemCode(),
            po.getRequisition().getQuantity(),
            po.getStatus(),
            po.getDateIssued()
        });
    }
}

    private void processPaymentForSelected() {
    int row = tblRecords.getSelectedRow();
    if (row < 0) return;
    int poId = (int) tableModel.getValueAt(row, 0);
    PurchaseOrder po = poMgr.findById(poId);
    po.setStatus("PAID");
    JOptionPane.showMessageDialog(this, "Payment processed for PO #" + po.getId());
    loadPendingOrders();
}

    private void showReportDialog() {
        // you can pop up a JSpinner-based date range selector here
    JOptionPane.showMessageDialog(this, "Report feature coming soon!");
}

    
    private void loadPendingPRs() {
        // e.g. jTable1.setModel( new MyTableModel(prMgr.getAll()) );
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLoadPOs = new javax.swing.JButton();
        btnLoadPRs = new javax.swing.JButton();
        btnApprovePO = new javax.swing.JButton();
        btnProcessPay = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnLoadPOs.setText("Load Orders");
        btnLoadPOs.setActionCommand("Load Orders");
        btnLoadPOs.setFocusable(false);
        btnLoadPOs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoadPOs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoadPOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadPOsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLoadPOs);

        btnLoadPRs.setText("Load Requisitions");
        btnLoadPRs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadPRsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLoadPRs);

        btnApprovePO.setText("Approve PO");
        btnApprovePO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnApprovePO.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnApprovePO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovePOActionPerformed(evt);
            }
        });
        jToolBar1.add(btnApprovePO);

        btnProcessPay.setText("Process Payment");
        btnProcessPay.setFocusable(false);
        btnProcessPay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProcessPay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProcessPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessPayActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProcessPay);

        btnReport.setText("Generate Report");
        btnReport.setFocusable(false);
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReport);

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRecords);

        jToolBar1.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadPOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadPOsActionPerformed
         loadPendingRequisitions();
    }//GEN-LAST:event_btnLoadPOsActionPerformed

    private void btnApprovePOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovePOActionPerformed
        approveSelected();
    }//GEN-LAST:event_btnApprovePOActionPerformed

    private void btnLoadPRsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadPRsActionPerformed
        loadPendingOrders();
    }//GEN-LAST:event_btnLoadPRsActionPerformed

    private void btnProcessPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessPayActionPerformed
        processPaymentForSelected();
    }//GEN-LAST:event_btnProcessPayActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        showReportDialog(); 
    }//GEN-LAST:event_btnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprovePO;
    private javax.swing.JButton btnLoadPOs;
    private javax.swing.JButton btnLoadPRs;
    private javax.swing.JButton btnProcessPay;
    private javax.swing.JButton btnReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblRecords;
    // End of variables declaration//GEN-END:variables
}
